name: Docker Image CI

on:
  push:
    branches: [ master,test ]
  pull_request:
    branches: [ master,test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup QEMU
        # You may pin to the exact commit or the version.
        # uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        uses: docker/setup-qemu-action@v1.2.0
        with:
          # QEMU static binaries Docker image (e.g. tonistiigi/binfmt:latest)
          image: arm64_test
          # Platforms to install (e.g. arm64,riscv64,arm)
          platforms: arm64
#     - name: Build the Docker image
#       run: |
#         docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#         docker build . --file Dockerfile --tag my-image-name:$(date +%s)
